# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

authentication_request:
  url:   /authentication
  param: { module: authentication, action: request }
  class: sfRequestRoute
  requirements:
    sf_method: [POST]

users_index:
  url:   /users
  param: { module: users, action: index }
  class: sfRequestRoute
  requirements:
    sf_method: [POST]