<?php

/**
 * sf_guard_user
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    G-test-project
 * @subpackage model
 * @author     alix.chaysinh@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sf_guard_user extends Basesf_guard_user
{
}
