<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    /**
     * Retrieves an admin by email_address and is_active flag and password.
     *
     * @param string $email
     *
     * @return sfGuardUser
     */
    public function findOneAdminByEmail($email)
    {
        $query = $this->createQuery('u')
            ->leftJoin('u.Groups g on g.name = ?', sfGuardGroupTable::NAME_ADMINS)
            ->where('u.email_address = ?', $email)
            ->addWhere('u.is_active = ?', true)
        ;

        return $query->fetchOne();
    }
}