<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    G-test-project
 * @subpackage model
 * @author     alix.chaysinh@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    /**
     * Add User group for every user inserted
     *
     * @param mixed $event event
     *
     * @return void
     */
    public function postInsert($event)
    {
        $this->addGroupByName(sfGuardGroupTable::NAME_USERS);
        $this->loadGroupsAndPermissions();
    }
}
